// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0j90KWwIKeohbgrneTp_Fr-68yBXb0qM',
    appId: '1:804405262100:android:51834231b26ac568953401',
    messagingSenderId: '804405262100',
    projectId: 'todoapp-firebase-79886',
    databaseURL: 'https://todoapp-firebase-79886-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoapp-firebase-79886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAawYhDqZFfZkCyXRsR8SYr5IqcZLN3stU',
    appId: '1:804405262100:ios:c7d985df107de01f953401',
    messagingSenderId: '804405262100',
    projectId: 'todoapp-firebase-79886',
    databaseURL: 'https://todoapp-firebase-79886-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoapp-firebase-79886.appspot.com',
    iosBundleId: 'com.example.musicapp',
  );
}
